name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: triston-site

      - name: Build Angular application
        run: npm run build -- --output-path=docs --base-href=/necroTriston/
        working-directory: triston-site

      - name: Disable Jekyll
        run: touch .nojekyll
        working-directory: triston-site/docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: triston-site/docs
