name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js with Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Explicitly use Node.js 20
          cache: 'npm'     # Enable caching for npm dependencies

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd triston-site
          npm ci # Use clean install for a consistent environment

      # Step 4: Build the Angular application
      - name: Build Angular application
        run: |
          cd triston-site
          npm run build -- --output-path=docs --base-href=/necroTriston/

      # Step 5: Disable Jekyll
      - name: Disable Jekyll
        run: |
          cd triston-site/docs
          touch .nojekyll

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: triston-site/docs
